version: '3'

services:
  db:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: testapp
    ports:
      - "3308:3306"

  topcons:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/topcons
    working_dir: /app
    command: /topcons/dockerrun.sh
    ports:
      - "8000:8000"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: testapp
    depends_on:
      - db
    network_mode: 'host'

